version: '3'

services:
  api:
    build: ./api
    env_file:
      - ./environment/api.env
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
    command: node server.js
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - ./environment/mongodb.env
    volumes:
      - ./docker-entrypoint-initdb.d/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    ports:
      - 27017:27017

volumes:
  astro-mongo-storage:
